// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKgw7E4TfjB1s4KA51cGVdHwJFjctfKP8',
    appId: '1:24779282424:web:9def2b885944ceca13e80d',
    messagingSenderId: '24779282424',
    projectId: 'fluttertodo-ac553',
    authDomain: 'fluttertodo-ac553.firebaseapp.com',
    storageBucket: 'fluttertodo-ac553.appspot.com',
    measurementId: 'G-WGNSHW03SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAW-Bn0U12QGs9AITIwcdrfVrpEVbuTgI',
    appId: '1:24779282424:android:076004f78f87a1eb13e80d',
    messagingSenderId: '24779282424',
    projectId: 'fluttertodo-ac553',
    storageBucket: 'fluttertodo-ac553.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvbgyKtM9n7BLgrpFmDb2GjL-Zm7NNiT0',
    appId: '1:24779282424:ios:1109d683d9ce8ee813e80d',
    messagingSenderId: '24779282424',
    projectId: 'fluttertodo-ac553',
    storageBucket: 'fluttertodo-ac553.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvbgyKtM9n7BLgrpFmDb2GjL-Zm7NNiT0',
    appId: '1:24779282424:ios:d5d5b1a312dfd73013e80d',
    messagingSenderId: '24779282424',
    projectId: 'fluttertodo-ac553',
    storageBucket: 'fluttertodo-ac553.appspot.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
